image: ros:humble-ros-base
volumes:
  - "/home/flavio/Scrivania/RoboCup/spqrbooster2026/src/SimBridge/bridge_colcon/install:/app/bridge_colcon"
  - "/home/flavio/Scrivania/Esperimenti_Booster/isaac/pippo:/app/pippo"
  - "/home/flavio/Scrivania/RoboCup/spqrbooster2026/src/SimBridge/bridge_ros/build:/app/bridge_ros"
  - "/home/flavio/Scrivania/RoboCup/spqrbooster2026/src/SimBridge/ros_dummy/build:/app/ros_dummy"
  